# Site settings
title:          Marcos Ramon
description:    "Textos e podcasts sobre filosofia, arte, tecnologia"
baseurl:        "/"
url:            "https://marcosramon.net"

# Google Analytics
google_analytics: UA-25904919-5

# Author
author:
  name:         Marcos Ramon
  url:          https://marcosramon.net
  email:        contato@marcosramon.net

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:title/
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         mramon
